import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className={"lcars-app-container"}>
          <div id="header" className={"lcars-row header"}>
            <div
              className={"lcars-elbow left-bottom lcars-golden-tanoi-bg"}
            ></div>

            <div className={"lcars-bar horizontal"}>
              <div className={"lcars-title right"}>LCARS</div>
            </div>

            <div className={"lcars-bar horizontal right-end decorated"}></div>
          </div>
          <div id="left-menu" className={"lcars-column start-space lcars-u-1"}>
            <a href="#container">
              <div className={"lcars-element button lcars-chestnut-rose-bg"}>
                TOP
              </div>
            </a>
            <a href="#layout_section">
              <div className={"lcars-element button"}>Layout</div>
            </a>
            <a href="#grid_section">
              <div className={"lcars-element button"}>Grid</div>
            </a>
            <a href="#colors_section">
              <div className={"lcars-element button"}>Colors</div>
            </a>
            <a href="#hyperlinks_section">
              <div className={"lcars-element button"}>Links</div>
            </a>
            <a href="#bar_section">
              <div className={"lcars-element button"}>Bar</div>
            </a>
            <a href="#textbox_section">
              <div className={"lcars-element button"}>Text Box</div>
            </a>
            <a href="#element_section">
              <div className={"lcars-element button"}>Element</div>
            </a>
            <a href="#elbow_section">
              <div className={"lcars-element button"}>Elbow</div>
            </a>
            <a href="#brackets_section">
              <div className={"lcars-element button"}>Brackets</div>
            </a>
            <a href="#inputs_section">
              <div className={"lcars-element button"}>INPUTS</div>
            </a>
            <a href="#table_section">
              <div className={"lcars-element button"}>TABLE</div>
            </a>
            <a href="#audio_section">
              <div className={"lcars-element button lcars-pale-canary-bg"}>
                Audio
              </div>
            </a>
            <a href="#svg_section">
              <div className={"lcars-element button lcars-pale-canary-bg"}>
                SVG
              </div>
            </a>
            <a href="#" target="_blank">
              <div className={"lcars-element button lcars-lavender-purple-bg"}>
                SRC
              </div>
            </a>

            <div className={"lcars-bar lcars-u-1"}></div>
          </div>
          <div id="footer" className={"lcars-row "}>
            <div className={"lcars-elbow left-top lcars-golden-tanoi-bg"}></div>

            <div className={"lcars-bar horizontal both-divider bottom"}></div>

            <div
              className={"lcars-bar horizontal right-end left-divider bottom"}
            ></div>
          </div>
          <div id="container">
            <div className={"lcars-column lcars-u-5"}>
              <h1>LCARS</h1>

              <p>
                LCARS is a purely client-side CSS and HTML framework, similar to
                Bootstrap, Foundation, Topcoat, Brick, or Pure to create user
                interfaces similiar to a certain popular sci-fi franchise.
                Enjoy!
              </p>
              <p>
                There are a few requirements in terms of HTML element nesting
                and corresponding CSS classes that are necessary for the styling
                to apply correctly. Looking directly at the source of this
                demonstration/documentation page should prove instructive. You
                might even use a copy of this page as a sort of a template; just
                delete and replace the parts you do not want.
              </p>
              <p>
                Each of the following sections will specify a primary CSS class
                name (in blue colored text) to assign to an HTML element to
                apply the appropriate CSS styling rules to achieve the described
                effect. Many primary classes will also have a list of secondary
                modifier class names (in red colored text) that can be appended
                to the class list to give additional styling options. Note that
                CSS classes are cumulative and cascading; i.e., you can combine
                them and the styling effects will (mostly) be inherited by the
                descendent nested-within html elements.
              </p>
              <h2 id="layout_section">Layout</h2>

              <span>
                Class:{" "}
                <pre className={"lcars-dodger-blue-color"}>lcars-row</pre>
              </span>
              <p>
                <a>Creates a row layout.</a>

                <ul>
                  <li>
                    <span>
                      <pre className={"lcars-rust-color"}>fill</pre>: fill
                      available space in column or row
                    </span>
                  </li>
                  <li>
                    <span>
                      <pre className={"lcars-rust-color"}>centered</pre>: center
                      content horizontally
                    </span>
                  </li>
                  <li>
                    <span>
                      <pre className={"lcars-rust-color"}>full-centered</pre>:
                      center content horizontally and vertically
                    </span>
                  </li>
                  <li>
                    <span>
                      <pre className={"lcars-rust-color"}>right</pre>: align
                      content to the right
                    </span>
                  </li>
                  <li>
                    <span>
                      <pre className={"lcars-rust-color"}>right-centered</pre>:
                      align content to the right and center vertically
                    </span>
                  </li>
                  <li>
                    <span>
                      <pre className={"lcars-rust-color"}>right-bottom</pre>:
                      align content to the bottom and to the right
                    </span>
                  </li>
                </ul>
              </p>
              <span>
                Class:{" "}
                <pre className="lcars-dodger-blue-color">lcars-column</pre>
              </span>
              <p>
                <a>Creates a column layout.</a>

                <ul>
                  <li>
                    <span>
                      <pre className={"lcars-rust-color"}>fill</pre>: fill
                      available space in column or row
                    </span>
                  </li>
                  <li>
                    <span>
                      <pre className={"lcars-rust-color"}>centered</pre>: center
                      content vertically
                    </span>
                  </li>
                  <li>
                    <span>
                      <pre className={"lcars-rust-color"}>full-centered</pre>:
                      center content horizontally and vertically
                    </span>
                  </li>
                  <li>
                    <span>
                      <pre className={"lcars-rust-color"}>centered-right</pre>:
                      align content to the right and center vertically
                    </span>
                  </li>
                  <li>
                    <span>
                      <pre className={"lcars-rust-color"}>bottom</pre>: align
                      content to the bottom
                    </span>
                  </li>
                  <li>
                    <span>
                      <pre className={"lcars-rust-color"}>bottom-centered</pre>:
                      align content to the bottom and center horizontally
                    </span>
                  </li>
                  <li>
                    <span>
                      <pre className={"lcars-rust-color"}>left-menu</pre>: add
                      margin to right to align in left elbow
                    </span>
                  </li>
                  <li>
                    <span>
                      <pre className={"lcars-rust-color"}>right-menu</pre>: add
                      margin to left to align in right elbow
                    </span>
                  </li>
                </ul>
              </p>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
